### ISSUE TITLE
Programma te groot voor Arduino Mega

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/HetRoversnest#13]
Oplossing: gebruik een SD kaart shield. Ik wijzig de architectuur wel efkes.

**Comment by sanderkooi45** [comment]
Fijn dat het waarschijnlijk zo wel gaat werken.

Sander 

Verstuurd vanaf mijn iPhone

**Comment by richelbilderbeek** [comment]
Ha, dit gaat werken!

Nieuwe werkwijze: in de folder `Bestanden` staat de tekst van elk hoofdstuk als tekst. Wil je bijvoorbeeld hoofdstuk 123 maken, maak dan een tekstbestand aan `123.txt` en zet hierin de tekst.
