### ISSUE TITLE
English: create Qt version

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/HetRoversnest#23]
Ask @modanung for the graphics of the items.

**Comment by Modanung** [comment]
[These](https://github.com/richelbilderbeek/HetRoversnest/blob/master/Voorwerpnummers.md) items?

**Comment by richelbilderbeek** [comment]
[These items](https://github.com/richelbilderbeek/HetRoversnest/blob/master/QtCreator/item.h) are the items really used.

**Comment by richelbilderbeek** [comment]
First version working:

![screenshotdesktop](https://cloud.githubusercontent.com/assets/2098230/8893307/e522f93a-338b-11e5-88bc-eb5dba02d1e6.png)

**Comment by richelbilderbeek** [comment]
Crosscompiled to Windows executables and made a webpage: 

http://richelbilderbeek.nl/GameCityOfThieves.htm

Done.
