### ISSUE TITLE
Put game in package manager

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/HetRoversnest#29]
I would like people to be able to do 

```
sudo apt-get install city-of-thieves-terminal
sudo apt-get install city-of-thieves-gui
```

Then run with:

```
./city-of-thieves-terminal
./city-of-thieves-gui
```

Ask @hertog6 for help.

**Comment by hertog6** [comment]
For the people who need an intro in Debian packaging; https://wiki.debian.org/IntroDebianPackaging

**Comment by richelbilderbeek** [comment]
It works!

Note to self: do this in `cityofthieves/debian`:

```
debuild -us -uc 
```

In the folder `cityofthieves` on can do:
```
sudo dpkg -i ../cityofthieves_1.0-1_i386.deb
```

**Comment by richelbilderbeek** [comment]
This issue was moved to richelbilderbeek/CityOfThieves#3
